# Generated by Django 4.1.7 on 2023-02-16 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(choices=[('servico1', 'limpeza simples'), ('servico2', 'limpeza profunda')], max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('forma_de_pagamento', models.CharField(choices=[('forma1', 'Espécie'), ('forma2', 'Cartão de Crédito'), ('forma3', 'Cartão de Débito'), ('forma4', 'PIX'), ('forma5', 'Cheque')], max_length=20)),
                ('data_de_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_do_servico', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('status1', '(pendente'), ('status2', 'realizado'), ('status3', 'cancelado)')], max_length=20)),
                ('nome_do_cliente', models.TextField()),
                ('telefone_do_cliente', models.TextField()),
                ('endereço_do_cliente', models.TextField()),
                ('atendente', models.ForeignKey(limit_choices_to={'groups__name': 'atendentes'}, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos_criados', to=settings.AUTH_USER_MODEL)),
                ('helper', models.ForeignKey(limit_choices_to={'groups__name': 'helpers'}, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos_executados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
